#!/bin/bash


./foo /coconut/3pk.bch $1
./foo /coconut/3pk-borne.bch $1
./foo /coconut/aircraftb.bch $1
./foo /coconut/avgasa.bch $1
./foo /coconut/avgasb.bch $1
./foo /coconut/avion2.bch $1
./foo /coconut/batch.bch $1
./foo /coconut/brownal.bch $1
./foo /coconut/catena.bch $1
./foo /coconut/concon.bch $1
./foo /coconut/core1.bch $1
./foo /coconut/cresc4.bch $1
./foo /coconut/dipigri.bch $1
./foo /coconut/disc2.bch $1
./foo /coconut/discs.bch $1
./foo /coconut/dixchlng.bch $1
./foo /coconut/dnieper.bch $1
./foo /coconut/Doxyfile.bch $1
./foo /coconut/dualc1.bch $1
./foo /coconut/dualc2.bch $1
./foo /coconut/dualc5.bch $1
./foo /coconut/dualc8.bch $1
./foo /coconut/eigencco.bch $1
./foo /coconut/eigmaxc.bch $1
./foo /coconut/eigminc.bch $1
./foo /coconut/ex2_1_7.bch $1
./foo /coconut/ex2_1_8.bch $1
./foo /coconut/fccu.bch $1
./foo /coconut/genhs28.bch $1
./foo /coconut/haifas.bch $1
./foo /coconut/haldmads.bch $1
./foo /coconut/himmelbk.bch $1
./foo /coconut/hs056.bch $1
./foo /coconut/hs070.bch $1
./foo /coconut/hs087.bch $1
./foo /coconut/hs088.bch $1
./foo /coconut/hs089.bch $1
./foo /coconut/hs090.bch $1
./foo /coconut/hs091.bch $1
./foo /coconut/hs093.bch $1
./foo /coconut/hs095.bch $1
./foo /coconut/hs096.bch $1
./foo /coconut/hs097.bch $1
./foo /coconut/hs098.bch $1
./foo /coconut/hs099.bch $1
./foo /coconut/hs100.bch $1
./foo /coconut/hs101.bch $1
./foo /coconut/hs102.bch $1
./foo /coconut/hs103.bch $1
./foo /coconut/hs104.bch $1
./foo /coconut/hs106.bch $1
./foo /coconut/hs107.bch $1
./foo /coconut/hs108.bch $1
./foo /coconut/hs109.bch $1
./foo /coconut/hs110.bch $1
./foo /coconut/hs111.bch $1
./foo /coconut/hs112.bch $1
./foo /coconut/hs113.bch $1
./foo /coconut/hs114.bch $1
./foo /coconut/hs116.bch $1
./foo /coconut/hs117.bch $1
./foo /coconut/hs118.bch $1
./foo /coconut/hs119.bch $1
./foo /coconut/hs21mod.bch $1
./foo /coconut/launch.bch $1
./foo /coconut/loadbal.bch $1
./foo /coconut/lotschd.bch $1
./foo /coconut/makela3.bch $1
./foo /coconut/makela4.bch $1
./foo /coconut/matrix2.bch $1
./foo /coconut/mconcon.bch $1
./foo /coconut/mistake.bch $1
./foo /coconut/modele_opti.bch $1
./foo /coconut/model_opti.bch $1
./foo /coconut/odfits.bch $1
./foo /coconut/optcntrl.bch $1
./foo /coconut/optmass.bch $1
./foo /coconut/optprloc.bch $1
./foo /coconut/orthregb.bch $1
./foo /coconut/orthrege.bch $1
./foo /coconut/pentagon.bch $1
./foo /coconut/polak1.bch $1
./foo /coconut/polak2.bch $1
./foo /coconut/polak3.bch $1
./foo /coconut/polak4.bch $1
./foo /coconut/polak5.bch $1
./foo /coconut/polak6.bch $1
./foo /coconut/portfl1.bch $1
./foo /coconut/rk23.bch $1
./foo /coconut/robot.bch $1
./foo /coconut/s365mod.bch $1
./foo /coconut/ssnlbeam.bch $1
./foo /coconut/synthes1.bch $1



####./foo /coconut/3pk $1
####./foo /medium/alkyl.bch $1
####./foo /medium/alkylbis.bch $1
####./foo /medium/ex14_2_3.bch $1
####./foo /medium/ex14_2_7.bch $1
####./foo /medium/ex2_1_7.bch $1
####./foo /medium/ex2_1_8.bch $1
####./foo /medium/ex2_1_9.bch $1
####./foo /medium/ex2_1_9fact.bch $1
####./foo /medium/ex5_2_2_case3.bch $1
####./foo /medium/ex5_3_2.bch $1
####./foo /medium/ex6_1_3bis.bch $1
####./foo /medium/ex6_1_4.bch $1
####./foo /medium/ex6_2_12.bch $1
####./foo /medium/ex6_2_14.bch $1
####./foo /medium/ex7_3_4.bch $1
####./foo /medium/ex7_3_4bis.bch $1
####./foo /medium/ex7_3_5bis.bch $1
####./foo /medium/ex8_5_2_1.bch $1
####./foo /medium/haverly.bch $1
####./foo /medium/himmel16.bch $1
####./foo /medium/launch.bch $1
####./foo /medium/like-1.bch $1
####./foo /medium/like.bch $1
####
####./foo /hard/chembis.bch $1
####./foo /others/dualc1.bch $1
